//
//  Constants.swift
//  BLESampleApp
//
//  Created by Jefin Abdul Jaleel on 28/11/25.
//

enum Constants {
    static let startScan = "Start Scan"
    static let stopScan = "Stop Scan"
    static let playIcon = "play.fill"
    static let stopIcon = "stop.fill"
    static let scanningDevices = "Scanning for devices..."
    static let antennaIcon = "antenna.radiowaves.left.and.right"
    static let bleScanner = "BLE Scanner"
    static let devicesFound = "devices found"
    static let nearbyDevices = "Nearby Devices"
    static let wifiSlash = "wifi.slash"
    static let scanning = "Scanning..."
    static let emptyState = "No devices found."
    static let unknownDevice = "Unknown Device"
    static let rssiSuffix = "dBm"
    static let deviceDetails = "Device Details"
    static let generalTab = "General"
    static let dataTab = "Data"
    static let locationTab = "Location"
    static let wifi = "wifi"
    static let wifiOut = "wifi.exclamationmark"
    static let cpu = "cpu"
    static let arrow = "chevron.right"
    static let dots = "..."
    static let errorTitle = "Error"
    static let okButton = "OK"
    static let uuidLabel = "UUID"
    static let nameLabel = "Name"
    static let rssiLabel = "RSSI"
    static let discoveredLabel = "Discovered"
    static let connectableLabel = "Connectable"
    static let yes = "Yes"
    static let no = "No"
    static let coordinatesLabel = "Coordinates"
    static let latitudeLabel = "Latitude"
    static let longitudeLabel = "Longitude"
    static let altitudeLabel = "Altitude"
    static let locationUnavailable = "Location not available"
    static let antennaFillIcon = "antenna.radiowaves.left.and.right.circle.fill"
    static let signal = "Signal"
    static let locationFillIcon = "location.fill"
    static let infoIcon = "info.circle.fill"
    static let docIcon = "doc.text.fill"
}
